name: offers_awards
description: عروض و جوائز

publish_to: 'none'

version: 5.0.0+17.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  pull_to_refresh: ^2.0.0
    
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^2.6.0

  flutter_localization: ^0.1.13
  intl: ^0.18.0

  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  flutter_svg: ^2.0.7
  curved_navigation_bar: ^1.0.3

  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  pin_code_fields: ^8.0.1

  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  image_picker: ^1.0.1
  flutter_image_compress: ^2.0.4
  sn_progress_dialog: ^1.1.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  qr_flutter: ^4.1.0

  share_plus: ^7.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.1.12

  firebase_messaging: ^14.6.6
  firebase_core: ^2.15.1
  flutter_local_notifications: ^15.1.0+1

  timeago: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/svg/buttons/
    - assets/svg/empty/
    - assets/svg/icons/
    - assets/svg/icons/active/
    - assets/svg/social/
    - assets/svg/map/

  fonts:
    - family: Droid Arabic Kufi
      fonts:
        - asset: assets/fonts/DroidKufi-Regular.ttf
        - asset: assets/fonts/DroidKufi-Bold.ttf
          weight: 900
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
